# Generated by Django 6.0.6 on 2026-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_premiumarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(default='general', max_length=100)),
                ('required_role', models.CharField(default='admin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PremiumArticle',
        ),
    ]
